language: python
group: travis_latest
os: linux
dist: bionic

cache:
  directories:
    - $HOME/.cache/pip

# stages:
#   - name: Test installation
#   - name: Build from source

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

script:
  # - pytest
  - python3 --version