language: python
group: travis_latest
os: linux
dist: bionic

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

script:
  # - pytest
  - python3 --version